const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_POSTS: "GET_POST",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_NEW_POST: "GET_NEW_POST",

    GET_CATEGORIES: 'GET_CATEGORIES'
}

export default actionTypes